services:
  postgres:
    image: postgres:16
    container_name: postgres-registre
    environment:
      POSTGRES_DB: pointage
      POSTGRES_USER: moha
      POSTGRES_PASSWORD: mohaguindo
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U moha -d pointage"]
      interval: 5s
      timeout: 5s
      retries: 10

volumes:
  postgres_data:
