# Script de configuration rapide pour Render
# Instructions pour copier-coller les variables d'environnement

echo "=== Configuration Backend Render ==="
echo ""
echo "Variables à ajouter dans Render Dashboard (Environment Variables):"
echo ""
echo "DATABASE_URL=postgresql://votre_username:votre_password@votre_host_render:5432/votre_database"
echo "PORT=3003"
echo "NODE_ENV=production"
echo "SERVICE_MODE=production"
echo "RENDER=true"
echo ""
echo "JWT_SECRET=k7P8xQ2zR5vN9mF3hJ6tW1yG4cV8bX2zS5dE9gH4jK7pL3nO6qR1uY8iA0sD4fG"
echo "BADGE_SECRET=mN9vB2xQ5wZ8cF1hJ4kL7pO3rT6yU9iA2sD5eG8gH1jK4nQ7pV0bX3zS6dF9c"
echo ""
echo "CORS_ORIGIN=https://votre-frontend.netlify.app"
echo "FRONTEND_URL=https://votre-frontend.netlify.app"
echo "CORS_ALLOWED_ORIGINS=https://votre-frontend.netlify.app"
echo ""
echo "BCRYPT_ROUNDS=12"
echo "SESSION_TIMEOUT=3600000"
echo "RATE_LIMIT_WINDOW=900000"
echo "RATE_LIMIT_MAX=100"
echo ""
echo "DEBUG=false"
echo "LOG_LEVEL=info"
echo ""
echo "=== Configuration Frontend Netlify ==="
echo ""
echo "Variables à ajouter dans Netlify Dashboard (Environment Variables):"
echo ""
echo "VITE_API_URL=https://votre-service-backend.onrender.com"
echo "VITE_BACKEND_URL=https://votre-service-backend.onrender.com"
echo "VITE_API_ENDPOINT=https://votre-service-backend.onrender.com/api"
echo ""
echo "VITE_APP_NAME=Registre Employé"
echo "VITE_APP_VERSION=1.0.0"
echo "VITE_NODE_ENV=production"
echo "VITE_SERVICE_MODE=production"
echo ""
echo "VITE_API_TIMEOUT=30000"
echo "VITE_REQUEST_TIMEOUT=30000"
echo ""
echo "VITE_ENABLE_ANALYTICS=true"
echo "VITE_ENABLE_ERROR_REPORTING=true"
echo "VITE_ENABLE_DEBUG=false"
echo ""
echo "VITE_DASHBOARD_REFRESH_INTERVAL=30000"
echo "VITE_NOTIFICATION_CHECK_INTERVAL=15000"
echo ""
echo "=== URLs à remplacer ==="
echo ""
echo "1. Remplacez 'votre-service-backend.onrender.com' par votre URL Render réelle"
echo "2. Remplacez 'votre-frontend.netlify.app' par votre URL Netlify réelle"
echo "3. Remplacez la DATABASE_URL par votre vraie URL PostgreSQL Render"
echo ""
echo "=== Étapes finales ==="
echo ""
echo "1. Ajoutez les variables dans Render Dashboard"
echo "2. Ajoutez les variables dans Netlify Dashboard"
echo "3. Redémarrez le service Render"
echo "4. Trigger un nouveau déploiement Netlify"
echo "5. Testez: https://votre-frontend.netlify.app"
